#配置数据源
spring:
  datasource:
    name: mengtian
    url: jdbc:mysql://192.168.40.14:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #activeMQ 配置
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.248.130:61616
    pool:
      enabled: true
      max-connections: 10
  redis:
    database: 0
    host: 192.168.40.14
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

#activeMQ 队列
queueName: publish.queue
#activeMQ 主题
topicName: publish.topic

#mybatis 配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.aissue.springboot.entity

logging:
  config: classpath:logconfig/logback.xml



